language: lisp
sudo: required

git:
  submodules: true

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - sudo apt install $LISP
  - make -C servers deps

script:
  - make test
  
addons:
  srcclr: true
