(in-package :chatter)

(defun place-call ()
  (warn "not implemented"))
(defun answer-call ()
  (warn "not implemented"))
(defun send-sms ()
  (warn "not implemented"))
(defun send-mms-photo ()
  (warn "not implemented"))
(defun send-mms-audio ()
  (warn "not implemented"))
(defun send-call-to-voice-mail ()
  (warn "not implemented"))
(defun present-sms ()
  (warn "not implemented"))
(defun present-mms-photo ()
  (warn "not implemented"))
(defun present-mms-audio ()
  (warn "not implemented"))
(defun present-voice-mail ()
  (warn "not implemented"))
(defun present-mobile-conversation ()
  (warn "not implemented"))
(defun present-mobile-conversations ()
  (warn "not implemented"))
